# .gitlab-ci.yml

# MEREGE checking
# 파이프라인을 어떤 러너를 사용하여 실행할 것인지 정의합니다.
# 여기서는 도커 러너를 사용합니다.
image: docker:latest

# 작업의 정의는 stages 섹션에 있습니다.
stages:
  - build
  - test
  - deploy

# 각 작업은 jobs 섹션에서 정의됩니다.
# 이름을 부여하고 해당 작업이 속하는 단계를 지정합니다.
# 스크립트는 해당 작업이 수행할 명령을 포함합니다.
build_job:
  # 도커 파일을 빌드합니다.
  stage: build
  script:
    - ls
    - docker info
    - docker build -t cicd:latest .

# 테스트 코드를 실행합니다.
test_job:
  services:
    - docker:dind
  stage: test
  script:
    - python tests/test_main.py

# 테스트가 완료되면 배포 작업을 해줍니다. 
#TODO Docker hub 연동.
deploy_job:
  services:
    - docker:dind
  stage: deploy
  script:
    - docker run -it -d -p 38000:80 cicd:latest